name = "TyOOP"
uuid = "3b9f22f0-6341-49b1-bf86-b86a5cb3ef82"
authors = ["thautwarm <twshere@outlook.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1.5"
MacroTools = "0.5"
Reexport = "1"
MLStyle = "~0.4.12"
DataStructures = "0.17, 0.18, 0.19"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
